import ReactNativeBlobUtil from 'react-native-blob-util';
import { generateUuidV4 } from '../utils/uuid';

/**
 * The stable device_identifier for this Android installation.
 *
 * Persisted in this app's private storage via react-native-blob-util
 * (already a dependency, already used this way by files/folderIdentity.ts)
 * rather than adding AsyncStorage/MMKV for one value — a new technology
 * this milestone's scope doesn't call for (CLAUDE.md Rule 2); see
 * folderIdentity.ts's own doc comment for the same reasoning. Not a
 * secret — it's sent in plaintext in POST /pairing/request and stored
 * server-side purely as a lookup key
 * (backend/app/repositories/device_repository.py's get_by_identifier) — so
 * a non-cryptographic UUID v4 (utils/uuid.ts) is sufficient.
 *
 * Generated once, the first time this is ever called on a given install,
 * and reused for every later pairing attempt from that same install —
 * matching docs/13_Database_Design.md's documented contract ("a UUID
 * generated by the Android app itself on first install"). An earlier
 * version of this file generated a fresh UUID on every pairing attempt
 * instead: because Session (session/secureStorage.ts) only persists
 * device_identifier as part of a successful pairing's credentials, any
 * re-pair not preceded by a full app reinstall (a session simply expiring,
 * or the desktop user clicking Remove and the same phone re-pairing) minted
 * a brand new identifier — and therefore a brand new backend Device row —
 * every time, accumulating stale duplicates the backend had no way to
 * reconcile (docs/15_QA_NOTEBOOK.md's P43 entry). Persisting it
 * independently of Session fixes that: the backend now recognizes a
 * re-pair from the same install as the same device_identifier and
 * reconciles in place (PairingService.approve_pairing) instead of creating
 * a new row.
 *
 * Still lost on app uninstall (private storage is wiped by the OS along
 * with everything else this app owns) — intentional, not a gap: Android
 * gives this app no stable, privacy-appropriate hardware identifier that
 * survives a reinstall, so a fresh install is, correctly, a fresh identity.
 * See docs/15_QA_NOTEBOOK.md's P43 entry for the full reasoning.
 */

const IDENTITY_PATH = `${ReactNativeBlobUtil.fs.dirs.DocumentDir}/relay-device-identity.json`;

// Deliberately no in-memory cache: this is only ever called once per
// pairing attempt (never a hot path), so a plain file read each time is
// simpler than a module-level singleton and keeps this file trivial to
// test in isolation.
export async function getOrCreateDeviceIdentifier(): Promise<string> {
  const stored = await readStoredIdentifier();
  if (stored) {
    return stored;
  }

  const generated = generateUuidV4();
  await ReactNativeBlobUtil.fs.writeFile(
    IDENTITY_PATH,
    JSON.stringify({ device_identifier: generated }),
    'utf8'
  );
  return generated;
}

async function readStoredIdentifier(): Promise<string | null> {
  try {
    const raw = await ReactNativeBlobUtil.fs.readFile(IDENTITY_PATH, 'utf8');
    const parsed = JSON.parse(raw) as { device_identifier?: unknown };
    return typeof parsed.device_identifier === 'string' && parsed.device_identifier.length > 0
      ? parsed.device_identifier
      : null;
  } catch {
    // No file yet (first-ever pairing attempt on this install) or a
    // corrupted one — either way, treated as "no identifier yet", exactly
    // like secureStorage.ts's own handling of an unreadable stored session.
    return null;
  }
}
